apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: metalmart
type: Opaque
stringData:
  postgres-password: "postgres"
  catalogue-url: "postgres://postgres:postgres@postgres:5432/catalogue?sslmode=disable"
  inventory-url: "postgres://postgres:postgres@postgres:5432/inventory?sslmode=disable"
  orders-url: "postgres://postgres:postgres@postgres:5432/orders?sslmode=disable"
