apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: metalmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - name: order-processor
        image: metalmart/order-processor:latest
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "order.created"
        - name: KAFKA_GROUP_ID
          value: "order-processor"
        - name: ORDER_SERVICE_URL
          value: "http://order:8084"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
