apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metalmart

resources:
  - namespace.yaml
  # Infrastructure
  - infrastructure/secrets.yaml
  - infrastructure/postgres.yaml
  - infrastructure/kafka.yaml
  # Services
  - catalogue/deployment.yaml
  - inventory/deployment.yaml
  - checkout/deployment.yaml
  - order/deployment.yaml
  - order-processor/deployment.yaml
  - frontend/deployment.yaml
